/**
 * /api/v1/contact-tags/ -- the tags a contact can carry.
 *
 * A full CRUD resource, unlike the read-only user-role catalogue: the backend
 * controller exposes read/create/update/delete, each behind its own
 * `totem.contacttag.*` scope.
 */

import { apiFetch, patchJson, postJson } from '@/api/client'
import { fetchAllPages, fetchList, type ListQuery, type Page } from '@/api/list'

/**
 * One row of the list.
 *
 * `color` is an INDEX into the front-end palette, not a CSS string: the backend
 * stores a small integer bounded 0..15 by a check constraint. See
 * `@/components/colors` for what an index paints as.
 *
 * A `type` and not an `interface`, for the same reason as CountryRef: only type
 * aliases get the implicit index signature that makes them assignable to
 * `RelationRecord`, which is what the relation widgets take.
 */
export type ContactTagRow = {
  /** A ULID, generated by the backend. */
  id: string
  name: string
  color: number
}

/**
 * List responses are serialised with `exclude_unset=True`, so ONLY the keys
 * asked for in `?fields=` come back. `satisfies` makes a typo here a compile
 * error rather than a silently missing column.
 */
export const CONTACT_TAG_LIST_FIELDS = [
  'id',
  'name',
  'color',
] as const satisfies readonly (keyof ContactTagRow)[]

/** Fields the backend accepts in `?ordering=`. Anything else is a 422. */
export const CONTACT_TAG_SORTABLE = ['name', 'color'] as const

/**
 * A `type` and not an `interface`: only type aliases get the implicit index
 * signature that makes them assignable to `ListFilters`.
 */
export type ContactTagFilters = {
  /** Matches the name, case-insensitive. */
  search?: string
  name?: string
}

export function listContactTags(
  query: ListQuery<ContactTagFilters>,
  signal?: AbortSignal,
): Promise<Page<ContactTagRow>> {
  return fetchList<ContactTagRow>('/contact-tags/', query, CONTACT_TAG_LIST_FIELDS, signal)
}

/**
 * The loader of the tags dropdown: `RelationFetch` shaped.
 *
 * `search` is the parameter name THIS endpoint uses, and the backend matches it
 * against the name, case-insensitively. A relation whose endpoint names its
 * filter differently passes its own function; nothing about the widget
 * hardcodes `search`.
 *
 * `CONTACT_TAG_LIST_FIELDS` already carries `color`, so the dots and the chips
 * are painted without asking for anything extra.
 *
 * No `ordering` is sent: the dropdown has to be sorted by what it DISPLAYS,
 * which is a client-side notion -- see toRelationOptions.
 */
export function searchContactTags(
  search: string | null,
  signal?: AbortSignal,
): Promise<ContactTagRow[]> {
  return fetchAllPages<ContactTagRow>(
    '/contact-tags/',
    CONTACT_TAG_LIST_FIELDS,
    { filters: { search } },
    signal,
  )
}

/**
 * The detail carries nothing the list row does not: the model has three fields.
 * Aliased rather than dropped so the form view reads like the contact one, and
 * so a widened schema has one place to grow.
 */
export type ContactTagDetail = ContactTagRow

/** No `?fields=` is sent on a detail: the whole record is wanted. */
export function fetchContactTag(id: string, signal?: AbortSignal): Promise<ContactTagDetail> {
  return apiFetch<ContactTagDetail>(`/contact-tags/${encodeURIComponent(id)}/`, { signal })
}

export interface ContactTagCreatePayload {
  /** Unique across the instance: a duplicate comes back as a field error. */
  name: string
  color?: number
}

/** `color` may be omitted: the create schema defaults it to 0, the first
    palette entry. */
export function createContactTag(payload: ContactTagCreatePayload): Promise<ContactTagDetail> {
  return postJson<ContactTagDetail>('/contact-tags/', payload)
}

/**
 * A PATCH body, and only the edited keys.
 *
 * The backend deserialises with `exclude_unset=True`: an omitted key is left
 * untouched, where an explicit `null` is written.
 */
export type ContactTagUpdatePayload = Partial<ContactTagCreatePayload>

export function updateContactTag(
  id: string,
  payload: ContactTagUpdatePayload,
): Promise<ContactTagDetail> {
  return patchJson<ContactTagDetail>(`/contact-tags/${encodeURIComponent(id)}/`, payload)
}
