/**
 * /api/v1/contacts/ -- the address book.
 *
 * The model flattens a postal address into the record (`AddressMixin`) and
 * carries a many-to-many to the tags. Neither `country` nor `tags` is editable
 * from the SPA yet: they are read on the list, never written.
 */

import { apiFetch, patchJson, postJson } from '@/api/client'
import { fetchList, type ListQuery, type Page } from '@/api/list'

/** A tag as it appears nested in a contact. Written as an id array, read as this. */
export interface ContactTagRef {
  id: string
  name: string
  /** Index into the front-end palette -- see @/components/form/fields/colors. */
  color: number
}

/** A country as it appears nested in a contact: the ISO code is aliased to `id`. */
export interface CountryRef {
  /** ISO 3166-1 alpha-2, e.g. 'BE'. */
  id: string
  name: string
}

export interface ContactRow {
  /** A ULID, generated by the backend. */
  id: string
  first_name: string | null
  /** The only mandatory field of the model. */
  last_name: string
  email: string | null
  mobile: string | null
  city: string | null
  tags: ContactTagRef[] | null
}

/**
 * List responses are serialised with `exclude_unset=True`, so ONLY the keys
 * asked for in `?fields=` come back. The address is deliberately reduced to
 * `city`: the rest of it belongs on the form, not in a table.
 */
export const CONTACT_LIST_FIELDS = [
  'id',
  'first_name',
  'last_name',
  'email',
  'mobile',
  'city',
  'tags',
] as const satisfies readonly (keyof ContactRow)[]

/**
 * Fields the backend accepts in `?ordering=`, restricted to the columns this
 * application actually displays. `tags` is deliberately absent: the backend
 * resolves every ordering field through `model._meta.get_field()`, which a
 * relation would not survive.
 */
export const CONTACT_SORTABLE = ['last_name', 'first_name', 'email', 'city'] as const

/**
 * A `type` and not an `interface`: only type aliases get the implicit index
 * signature that makes them assignable to `ListFilters`.
 */
export type ContactFilters = {
  /** Matches the first name, the last name OR the email, case-insensitive. */
  search?: string
  email?: string
  city?: string
  /** ISO 3166-1 alpha-2 code. */
  country?: string
  /** Id of a tag the contact must carry. */
  tag?: string
}

export function listContacts(
  query: ListQuery<ContactFilters>,
  signal?: AbortSignal,
): Promise<Page<ContactRow>> {
  return fetchList<ContactRow>('/contacts/', query, CONTACT_LIST_FIELDS, signal)
}

/** What GET /contacts/{id}/ returns. No `?fields=` is sent on a detail. */
export interface ContactDetail extends ContactRow {
  /** ISO `YYYY-MM-DD`: a calendar day, with no time and no timezone. */
  birth_date: string | null
  number: string | null
  street: string | null
  zip: string | null
  country: CountryRef | null
  create_date: string | null
  update_date: string | null
}

export function fetchContact(id: string, signal?: AbortSignal): Promise<ContactDetail> {
  return apiFetch<ContactDetail>(`/contacts/${encodeURIComponent(id)}/`, { signal })
}

/**
 * The create body.
 *
 * `country` and `tags` are absent on purpose: the form does not expose them
 * yet, so neither is ever sent -- see createContact for the one exception.
 */
export interface ContactCreatePayload {
  last_name: string
  first_name?: string | null
  email?: string | null
  mobile?: string | null
  birth_date?: string | null
  number?: string | null
  street?: string | null
  zip?: string | null
  city?: string | null
}

/**
 * `tags: []` is seeded the way createUser seeds `roles: []`: the create schema
 * has no default for the relation. A brand new contact has no tag anyway, so
 * this states the obvious rather than deciding anything.
 */
export function createContact(payload: ContactCreatePayload): Promise<ContactDetail> {
  return postJson<ContactDetail>('/contacts/', { tags: [], ...payload })
}

/**
 * A PATCH body, and only the edited keys.
 *
 * The backend deserialises with `exclude_unset=True`: an omitted key is left
 * untouched, where an explicit `null` is written. That is what keeps `tags` and
 * `country` safe -- an update never mentions them, so editing a phone number
 * cannot wipe a contact's tags.
 */
export type ContactUpdatePayload = Partial<ContactCreatePayload>

export function updateContact(
  id: string,
  payload: ContactUpdatePayload,
): Promise<ContactDetail> {
  return patchJson<ContactDetail>(`/contacts/${encodeURIComponent(id)}/`, payload)
}

// ------------------------------------------------------------- presentation

/** "Jane Doe", or just "Doe" -- only the last name is guaranteed to be there. */
export function displayName(contact: ContactRow): string {
  return contact.first_name ? `${contact.first_name} ${contact.last_name}` : contact.last_name
}

/** Up to two letters for an avatar. Falls back to '?' rather than to nothing. */
export function initials(contact: ContactRow): string {
  const letters = [contact.first_name, contact.last_name]
    .map((part) => part?.trim()?.[0] ?? '')
    .join('')
    .toUpperCase()
  return letters || '?'
}
