/**
 * /api/v1/website/menus/ -- the menu tree of the public website.
 *
 * A full CRUD resource: the backend controller exposes read/create/update/
 * delete, each behind its own `totem.websitemenu.*` scope.
 *
 * The model is `website.Menu` ("Menu Item"); only the scopes and the URL
 * prefix carry the `website` prefix. The trailing slash is required, on the
 * detail routes too.
 */

import { apiDelete, apiFetch, patchJson, postJson } from '@/api/client'
import { fetchAllPages, fetchList, type ListQuery, type Page } from '@/api/list'

import type { WebsitePageRef } from './websitePages'

/**
 * A menu item as the backend nests it (a parent), plus the materialised path
 * when it was asked for.
 *
 * A `type` and not an `interface`, for the same reason as CountryRef: only type
 * aliases get the implicit index signature that makes them assignable to
 * `RelationRecord`, which is what the relation widgets take.
 */
export type WebsiteMenuRef = {
  /** A ULID, generated by the backend. */
  id: string
  name: string
  /**
   * `<rootId>/<parentId>/<selfId>/` -- the whole ancestry INCLUDING this item's
   * own id, trailing slash included. Computed by the backend, ignored on write.
   * Only present when `?fields=` asked for it.
   */
  parent_path?: string
}

/** One row of the list. */
export type WebsiteMenuRow = {
  id: string
  name: string
  /** Ordering among siblings. Defaults to 20, not nullable. */
  sequence: number
  /** Relations are read as nested objects and written as ids. */
  parent: WebsiteMenuRef | null
  page: WebsitePageRef | null
  link: string | null
}

/**
 * List responses are serialised with `exclude_unset=True`, so ONLY the keys
 * asked for in `?fields=` come back -- and an unknown name is a 422, which is
 * why this list lives next to the endpoint. `satisfies` makes a typo here a
 * compile error rather than a silently missing column.
 */
export const WEBSITE_MENU_LIST_FIELDS = [
  'id',
  'name',
  'sequence',
  'parent',
  'page',
  'link',
] as const satisfies readonly (keyof WebsiteMenuRow)[]

/**
 * Fields the backend accepts in `?ordering=`. It also whitelists `create_date`,
 * which no column shows, and deliberately excludes `parent_path` and every
 * relation: asking for one of those is a 422.
 */
export const WEBSITE_MENU_SORTABLE = ['name', 'sequence'] as const

/**
 * Filters this endpoint accepts, as plain query params.
 *
 * `target_page` and not `page`: the endpoint already spends `page` on the
 * paginator. A `type` and not an `interface`: only type aliases get the
 * implicit index signature that makes them assignable to `ListFilters`.
 */
export type WebsiteMenuFilters = {
  /** Matches the name OR the link, case-insensitive. */
  search?: string
  name?: string
  /** The id of the direct parent. */
  parent?: string
  /** The id of the target page. */
  target_page?: string
}

export function listWebsiteMenus(
  query: ListQuery<WebsiteMenuFilters>,
  signal?: AbortSignal,
): Promise<Page<WebsiteMenuRow>> {
  return fetchList<WebsiteMenuRow>('/website/menus/', query, WEBSITE_MENU_LIST_FIELDS, signal)
}

/**
 * `parent_path` is asked for on top of the two keys the dropdown needs: it is
 * what isMenuDescendant reads to keep an item from being offered as its own
 * ancestor.
 */
export const WEBSITE_MENU_RELATION_FIELDS = [
  'id',
  'name',
  'parent_path',
] as const satisfies readonly (keyof WebsiteMenuRef)[]

/**
 * The loader of the parent dropdown: `RelationFetch` shaped.
 *
 * `search` is the parameter name THIS endpoint uses, and the backend matches it
 * against the name or the link, case-insensitively. Nothing about the widget
 * hardcodes that name.
 *
 * No `ordering` is sent: the dropdown has to be sorted by what it DISPLAYS,
 * which is a client-side notion -- see toRelationOptions. `name` is enough of a
 * label for the generic displayRelation, so no relationDisplay is needed.
 */
export function searchWebsiteMenus(
  search: string | null,
  signal?: AbortSignal,
): Promise<WebsiteMenuRef[]> {
  return fetchAllPages<WebsiteMenuRef>(
    '/website/menus/',
    WEBSITE_MENU_RELATION_FIELDS,
    { filters: { search } },
    signal,
  )
}

/** What GET /website/menus/{id}/ returns: the full MenuSchema. */
export type WebsiteMenuDetail = WebsiteMenuRow & {
  /** Computed by the backend; see WebsiteMenuRef. Ignored on write. */
  parent_path: string
  new_window: boolean
  create_date: string
}

/** No `?fields=` is sent on a detail: retrieve does not honour it anyway. */
export function fetchWebsiteMenu(id: string, signal?: AbortSignal): Promise<WebsiteMenuDetail> {
  return apiFetch<WebsiteMenuDetail>(`/website/menus/${encodeURIComponent(id)}/`, { signal })
}

/**
 * Body of POST /website/menus/.
 *
 * Only `name` is required; everything else has a default. Relations go out as
 * ids -- `parent` and `page` as bare ULIDs, never as the nested objects a GET
 * returns -- and `parent_path` is not accepted at all (sending it is silently
 * ignored).
 */
export interface WebsiteMenuCreatePayload {
  name: string
  /** Defaults to 20 server-side. Non-nullable. */
  sequence?: number
  parent?: string | null
  page?: string | null
  link?: string | null
  /** Non-nullable with a default: send `false`, never `null`. */
  new_window?: boolean
}

export function createWebsiteMenu(
  payload: WebsiteMenuCreatePayload,
): Promise<WebsiteMenuDetail> {
  return postJson<WebsiteMenuDetail>('/website/menus/', payload)
}

/**
 * A PATCH body, and only the edited keys.
 *
 * The backend deserialises with `exclude_unset=True`: an omitted key is left
 * untouched, where an explicit `null` is written. That is what makes
 * menuTargetPayload's `null` meaningful -- it is the only way to clear the
 * target the item no longer uses.
 *
 * Re-parenting recomputes `parent_path` for the whole subtree server-side, so a
 * cached child's path is stale after a move: refetch rather than patch it up.
 */
export type WebsiteMenuUpdatePayload = Partial<WebsiteMenuCreatePayload>

export function updateWebsiteMenu(
  id: string,
  payload: WebsiteMenuUpdatePayload,
): Promise<WebsiteMenuDetail> {
  return patchJson<WebsiteMenuDetail>(`/website/menus/${encodeURIComponent(id)}/`, payload)
}

/**
 * A menu item with children cannot be deleted: `parent` is
 * `on_delete=PROTECT`. The refusal comes back as an ApiError, so the caller
 * must show it rather than assume the row is gone.
 */
export function deleteWebsiteMenu(id: string): Promise<void> {
  return apiDelete(`/website/menus/${encodeURIComponent(id)}/`)
}

/**
 * Which of the two target fields a menu item uses.
 *
 * There is NO discriminator column: the backend's own `url` property reads
 * `page` first and falls back to `link`. So the type is deduced, never stored
 * -- see activeSwitchField, which does the deducing generically.
 */
export type MenuTargetType = 'page' | 'link'

/**
 * The two target keys, with the inactive one ALWAYS null.
 *
 * Load-bearing, in both directions:
 *
 *  - a <Field v-if> that is unmounted keeps its value in the draft, so a link
 *    typed and then abandoned would otherwise go out with the POST;
 *  - on a PATCH, `exclude_unset=True` means a target that is not mentioned is
 *    LEFT ALONE. Switching from a link to a page without an explicit
 *    `link: null` would store both, and the backend's check constraint accepts
 *    that ("at least one"), so nothing would complain -- the item would just
 *    keep a dead link nobody can see.
 */
export function menuTargetPayload(
  active: MenuTargetType,
  target: { page: string | null; link: string | null },
): { page: string | null; link: string | null } {
  return active === 'page'
    ? { page: target.page, link: null }
    : { page: null, link: target.link }
}

/**
 * Is this candidate unusable as the parent of `menuId` -- the item itself, or
 * one of its descendants?
 *
 * `parent_path` is the whole ancestry and it INCLUDES the item's own id, so a
 * single segment test covers both cases. The backend refuses either with a 422
 * on `parent` anyway; this only keeps an impossible choice out of the dropdown.
 *
 * A candidate whose `parent_path` was not requested cannot be judged, and is
 * kept: hiding a legitimate parent is worse than offering one the backend will
 * refuse.
 */
export function isMenuDescendant(candidate: WebsiteMenuRef, menuId: string): boolean {
  if (!menuId) return false
  if (candidate.id === menuId) return true
  if (typeof candidate.parent_path !== 'string' || candidate.parent_path === '') return false

  // Framed by slashes on both sides so `/01H.../` cannot match a longer id that
  // merely starts with the same characters.
  return `/${candidate.parent_path}`.includes(`/${menuId}/`)
}
