/**
 * /api/v1/website/pages/ -- the pages of the public website.
 *
 * A full CRUD resource: the backend controller exposes read/create/update/
 * delete, each behind its own `totem.websitepage.*` scope.
 *
 * Note the two-segment path: the controller's prefix is `/website/pages/`, not
 * `/website-pages/`. The trailing slash is required, on the detail routes too.
 */

import { apiDelete, apiFetch, patchJson, postJson } from '@/api/client'
import { fetchAllPages, fetchList, type ListQuery, type Page } from '@/api/list'
import type { RelationRecord } from '@/components/form/fields/many2one'

/**
 * The author of a page, as the backend nests it.
 *
 * `login` and not `username`: the ORM field is `username`, the API aliases it.
 *
 * A `type` and not an `interface`, for the same reason as CountryRef: only type
 * aliases get the implicit index signature that makes them assignable to
 * `RelationRecord`, which is what the relation widgets take.
 */
export type PageUserRef = {
  /** A UUID -- users are not ULID-keyed, unlike pages and menus. */
  id: string
  login: string
}

/** One row of the list. */
export type WebsitePageRow = {
  /** A ULID, generated by the backend. */
  id: string
  title: string
  /** The URL part. Unique across the instance, `^[-a-zA-Z0-9_]+$`. */
  slug: string
  is_published: boolean
}

/**
 * List responses are serialised with `exclude_unset=True`, so ONLY the keys
 * asked for in `?fields=` come back -- and an unknown name is a 422, which is
 * why this list lives next to the endpoint. `satisfies` makes a typo here a
 * compile error rather than a silently missing column.
 */
export const WEBSITE_PAGE_LIST_FIELDS = [
  'id',
  'title',
  'slug',
  'is_published',
] as const satisfies readonly (keyof WebsitePageRow)[]

/**
 * Fields the backend accepts in `?ordering=`. It also whitelists
 * `date_published` and `update_date`, which no column shows: asking for
 * anything outside its list is a 422, and `user` is not in it at all -- the
 * backend cannot order on a relation.
 */
export const WEBSITE_PAGE_SORTABLE = ['title', 'slug', 'is_published'] as const

/**
 * Filters this endpoint accepts, as plain query params.
 *
 * A `type` and not an `interface`: only type aliases get the implicit index
 * signature that makes them assignable to `ListFilters`.
 */
export type WebsitePageFilters = {
  /** Matches the title OR the slug, case-insensitive. */
  search?: string
  title?: string
  slug?: string
  is_published?: boolean
  /** The author's id. Named `author`, not `user`. */
  author?: string
}

export function listWebsitePages(
  query: ListQuery<WebsitePageFilters>,
  signal?: AbortSignal,
): Promise<Page<WebsitePageRow>> {
  return fetchList<WebsitePageRow>('/website/pages/', query, WEBSITE_PAGE_LIST_FIELDS, signal)
}

/**
 * What a page looks like when a menu item points at it: exactly the three keys
 * the backend nests, so the dropdown and the loaded value read alike.
 */
export type WebsitePageRef = {
  id: string
  title: string
  slug: string
}

export const WEBSITE_PAGE_RELATION_FIELDS = [
  'id',
  'title',
  'slug',
] as const satisfies readonly (keyof WebsitePageRef)[]

/**
 * The loader of the page dropdown on a menu item: `RelationFetch` shaped.
 *
 * `search` is the parameter name THIS endpoint uses, and the backend matches it
 * against the title or the slug, case-insensitively. Nothing about the widget
 * hardcodes that name -- an endpoint calling its filter otherwise passes its
 * own function.
 *
 * Drafts are returned too: the backend registers no access rule here, and a
 * menu may legitimately be prepared before the page goes live.
 *
 * No `ordering` is sent: the dropdown has to be sorted by what it DISPLAYS,
 * which is a client-side notion -- see toRelationOptions.
 */
export function searchWebsitePages(
  search: string | null,
  signal?: AbortSignal,
): Promise<WebsitePageRef[]> {
  return fetchAllPages<WebsitePageRef>(
    '/website/pages/',
    WEBSITE_PAGE_RELATION_FIELDS,
    { filters: { search } },
    signal,
  )
}

/**
 * The label of a page in a dropdown, and in a read-only relation field.
 *
 * The generic `displayRelation` reads `name`, which this model does not have:
 * its human key is `title`, with the slug as a fallback for the pathological
 * case of an empty one.
 */
export function displayPage(record: RelationRecord): string {
  const title = record.title
  if (typeof title === 'string' && title.trim() !== '') return title.trim()
  const slug = record.slug
  if (typeof slug === 'string' && slug.trim() !== '') return slug.trim()
  return String(record.id)
}

/**
 * What GET /website/pages/{id}/ returns: the full PageSchema, wider than the
 * row the list asks for.
 *
 * `date_published` is READ-ONLY -- it is absent from both write schemas and set
 * by the backend. `update_date` likewise.
 */
export type WebsitePageDetail = WebsitePageRow & {
  /** HTML, validated server-side against a tag whitelist. */
  content: string
  date_published: string | null
  update_date: string
  user: PageUserRef | null
}

/** No `?fields=` is sent on a detail: retrieve does not honour it anyway. */
export function fetchWebsitePage(id: string, signal?: AbortSignal): Promise<WebsitePageDetail> {
  return apiFetch<WebsitePageDetail>(`/website/pages/${encodeURIComponent(id)}/`, { signal })
}

/**
 * Body of POST /website/pages/.
 *
 * `title`, `slug` and `content` are required by the schema. `slug` is unique
 * across the instance through a UniqueConstraint, so a clash comes back as a
 * field error on `slug`; invalid HTML in `content` comes back on `content`.
 *
 * `date_published` is deliberately absent: the write schemas do not accept it.
 */
export interface WebsitePageCreatePayload {
  title: string
  slug: string
  content: string
  /** Non-nullable with a default: send `false`, never `null`. */
  is_published?: boolean
  /** The author's id, or `null`. Relations are written as ids. */
  user?: string | null
}

export function createWebsitePage(
  payload: WebsitePageCreatePayload,
): Promise<WebsitePageDetail> {
  return postJson<WebsitePageDetail>('/website/pages/', payload)
}

/**
 * A PATCH body, and only the edited keys.
 *
 * The backend deserialises with `exclude_unset=True`: an omitted key is left
 * untouched, where an explicit `null` is written.
 *
 * `is_published` matters more than the others: its MERE PRESENCE restamps
 * `date_published` to now, whichever way it is flipped
 * (`kwargs.setdefault("date_published", timezone.now())`). So it must reach
 * this body only when the user actually toggled it -- echoing it back unchanged
 * would rewrite the publication date of an untouched page.
 */
export type WebsitePageUpdatePayload = Partial<WebsitePageCreatePayload>

export function updateWebsitePage(
  id: string,
  payload: WebsitePageUpdatePayload,
): Promise<WebsitePageDetail> {
  return patchJson<WebsitePageDetail>(`/website/pages/${encodeURIComponent(id)}/`, payload)
}

/**
 * A page referenced by a menu item cannot be deleted: that FK is
 * `on_delete=PROTECT`. The refusal comes back as an ApiError, so the caller
 * must show it rather than assume the row is gone.
 */
export function deleteWebsitePage(id: string): Promise<void> {
  return apiDelete(`/website/pages/${encodeURIComponent(id)}/`)
}
